# Generated by Django 3.0.2 on 2020-01-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=10)),
                ('courseName', models.CharField(max_length=255)),
                ('coursePrice', models.CharField(max_length=10)),
                ('coursePaymentPeriod', models.CharField(max_length=10)),
            ],
        ),
    ]
